<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 ground.glb --transform
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'
  import { AutoColliders } from '@threlte/rapier'

  export const ref = new Group()

  const gltf = useGltf('/3d/ground-transformed.glb', { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
  <AutoColliders shape={'cuboid'}>
    <T.Mesh geometry={gltf.nodes.EXPORT_OSM_MAPNIK_WM.geometry} material={gltf.materials['rastMat.001']} />
</AutoColliders>
	{:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
