<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 groundv2.glb --transform
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'
  import { AutoColliders } from '@threlte/rapier'

  export const ref = new Group()

  const gltf = useGltf('/3d/groundv2-transformed.glb', { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
   <AutoColliders shape={'cuboid'}>
    <T.Mesh geometry={gltf.nodes.Terrain001.geometry} userData = {{ id: "ground"}} >
      <T.MeshStandardMaterial color={'#808080'} />
    </T.Mesh>
  </AutoColliders>
    {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
